version: "3.9"

services:
  db:
    image: mongo:5.0.10
    hostname: mongo
    ports:
      - "8050:27017"
    environment:
      - MONGO_INITDB_DATABASE=airsoft-iam
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/var/lib/mongodb/data/
    command: [--auth, "--bind_ip", "0.0.0.0"]
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:mongodb@db:27017/airsoft-iam
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mongodb_data:
