server:
  port: 8000
  servlet:
    context-path: /iam

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airsoft-iam
      username: mongodb
      password: mongodb

authentication:
  jwt:
    secret: "7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4"
    expiration: 120
