server:
  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:mongodb@localhost:8050/airsoft-iam
      auto-index-creation: true
  graphql:
    cors:
      allowed-origins: "*"
    graphiql:
      enabled: true
  kafka:
    bootstrap-servers: "localhost:9092"

grpc:
  server:
    port: 8010
    security:
      enabled: false

authentication:
  jwt:
    secret: "7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4"
    expiration: 120
