server:
  port: 8000
  servlet:
    context-path: /iam

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airsoft-iam
    username: postgres
    password: postgrespw
  liquibase:
    change-log: classpath:/db/master-changelog.xml

authentication:
  jwt:
    secret: "7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4-7c03cfe1-33d8-4301-8779-ce5c267cafb4"
    expiration: 120
